# Generated by Django 4.1.7 on 2023-03-16 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_generation', models.DateTimeField(auto_now_add=True)),
                ('header', models.CharField(max_length=250)),
                ('text_and_multimedia', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rev_status', models.BooleanField(default=False)),
                ('id_ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.ads')),
                ('id_users_rev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ads',
            name='id_categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.categories'),
        ),
        migrations.AddField(
            model_name='ads',
            name='id_users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
